### ISSUE TITLE
Depth API

### ISSUE THREAD

**Issue by KTRosenberg** [oculus-samples/Unity-TheWorldBeyond#18]
Do you plan to integrate the depth API into this project, or is it straightforward-enough to integrate based on the other sample repo?

**Comment by PanyaMeta** [comment]
Hello @KTRosenberg, thanks for the question. As it stands now, The World Beyond is primarily in maintenance mode. Depth API requires a few steps that we're still backlogged on; upgrading the Unity version and upgrading the Oculus SDK to v57. Specifically for The World Beyond, it can't incorporate Depth API because it's an experimental feature (and can't yet ship to the Store). But it should be straightforward to implement locally, and we would like to at least do the prior steps to this repo to make it easier (upgrade Unity & Oculus SDK).
